module

public import CategoricalLogic.Operad
public import CategoricalLogic.Profunctor.Basic
public import CategoricalLogic.Profunctor.Cells
public import CategoricalLogic.Profunctor.Product
-- import CategoricalLogic.Profunctor.Discrete
public import CategoricalLogic.Term
public import CategoricalLogic.VirtualDoubleCategory.QuiverSpan
public import CategoricalLogic.VirtualDoubleCategory.Paths
public import CategoricalLogic.VirtualDoubleCategory.PathsKleisli
public import CategoricalLogic.VirtualDoubleCategory.Basic
public import CategoricalLogic.VirtualDoubleCategory.SpanQuiv
