name = "categorical-logic"
defaultTargets = ["CategoricalLogic"]

[leanOptions]
# From Harmonic's header
autoImplicit = false
relaxedAutoImplicit = false

maxHeartbeats = 8000000
maxRecDepth = 4000
synthInstance.maxHeartbeats = 20000
synthInstance.maxSize = 128
grind.warning = false

# Pretty-printer settings
pp.unicode.fun = true # pretty-prints `fun a ↦ b`

# Harmonic sets this to true, but it is annoying
pp.fullNames = false
# Harmonic sets this to true, but it is annoying
pp.structureInstances = false
pp.coercions.types = true
pp.funBinderTypes = true
pp.letVarTypes = true
pp.piBinderTypes = true

[[require]]
name = "mathlib"
path = "../mathlib4"


[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"
[[lean_lib]]
name = "CategoricalLogic"
