/-
Copyright (c) 2026 Adrian Marti. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Adrian Marti, Aristotle
-/
module

public import CategoricalLogic.Profunctor.Basic
public import Mathlib.CategoryTheory.Category.Cat
public import Mathlib.Combinatorics.Quiver.Path
public import Mathlib.Logic.Relation

/-!
# Path Products and Tensor Products of Profunctors

This file defines the product of profunctor values along a path of profunctors,
the wedge relation identifying elements related by sliding morphisms at internal junctions,
and the functor tensor product as the quotient by this relation.

## Main definitions

* `ProfCat`: A wrapper around `Cat` with a quiver structure where edges are profunctors.
* `PathProd`: The product of profunctor values along a path of profunctors.
* `WedgeRel`: An inductive relation on `PathProd` identifying tuples related by
  wedge conditions.
* `PathProd.setoid`: The setoid generated by `WedgeRel`.
* `TensorProd`: The functor tensor product, defined as the quotient of `PathProd`
  by `WedgeRel`.
* `TensorProd.toProfunctor`: The profunctor structure on the tensor product.

## Design notes

The base case of `PathProd` for the empty path `.nil` uses `ULift (c ⟶ d)`. This ensures
that a cell from the empty path to `K` is equivalent to a dinatural element (unit) of `K`,
and a cell from a singleton path `[H]` to `K` is equivalent to a natural transformation from
`H` to `K`.

The first argument of `PathProd` is the target boundary and the second is the source boundary,
matching the convention of `Profunctor.obj` where the first argument is from the contravariant
side.

An edge from `C` to `D` in `ProfCat` is a `Profunctor D C`, which represents a profunctor
from `C` to `D` (contravariant in `C`, covariant in `D`). This choice ensures that the
`mapL` and `mapR` operations on profunctors directly give the correct actions on `PathProd`
boundaries.
-/

@[expose] public section

namespace CategoryTheory

universe u v

/-! ## The profunctor category -/

/-- `ProfCat` is a wrapper around `Cat` equipped with a quiver structure where
an edge from `C` to `D` is a profunctor `Profunctor D C`.

While `Cat` uses functors as morphisms (and has a `Category` instance), `ProfCat`
uses profunctors as edges (and only has a `Quiver` instance). -/
structure ProfCat.{v', u'} where
  /-- The underlying category. -/
  toCat : Cat.{v', u'}

instance : CoeSort ProfCat.{v, u} (Type u) where
  coe C := C.toCat

/-- The quiver structure on `ProfCat`: an edge from `C` to `D` is a profunctor
`Profunctor D C` (covariant in `D`, contravariant in `C`), representing a profunctor
from `C` to `D`. -/
instance : Quiver ProfCat.{v, u} where
  Hom C D := Profunctor.{v} C D

/-! ## Path products -/

/-- The product of profunctor values along a path of profunctors.

For the empty path (`.nil : Path C C`), `PathProd .nil d c = ULift (c ⟶ d)`, recording
a morphism from `c` to `d` in the category `C`.

For a path `.cons p H` ending with profunctor `H : Profunctor D E` (edge from `E` to `D`),
`PathProd (.cons p H) d c = Σ (e : E), PathProd p e c × H.obj e d`, quantifying over the
intermediate object `e` where the sub-path `p` meets `H`. -/
def PathProd {C D : ProfCat.{v, u}} :
    Quiver.Path C D → D → C → Type (max u v)
  | .nil, d, c => ULift.{u} (d ⟶ c)
  | @Quiver.Path.cons _ _ _ E _ p H, d, c => Σ (e : E), H.obj d e × PathProd p e c

namespace PathProd

/-- Left action on `PathProd`: precomposes a morphism on the source (left) boundary.
Given `α : c' ⟶ c`, maps `PathProd p d c → PathProd p d c'`. This is contravariant:
the morphism goes `c' → c` but the map goes from values at `c` to values at `c'`. -/
def mapL {C D : ProfCat.{v, u}} {d d' : D} {c : C}
    {p : Quiver.Path C D} (args : PathProd p d c) (α : d' ⟶ d) : PathProd p d' c :=
    -- match p with
  -- | Quiver.Path.nil => sorry
  match D, p, d, d', args, α with
  | _, .nil, _, _, ⟨f⟩, α => ⟨α ≫ f⟩
  | _, @Quiver.Path.cons _ _ _ _ _ _ H, _, _, args, α =>
    let ⟨e, h, inner⟩ := args
    ⟨e, H.mapL α h, inner⟩

/-- Right action on `PathProd`: postcomposes a morphism on the target (right) boundary.
Given `α : d ⟶ d'`, maps `PathProd p d c → PathProd p d' c`. This is covariant. -/
def mapR {C D : ProfCat.{v, u}} {d : D} {c c' : C}
    {p : Quiver.Path C D} (args : PathProd p d c) (α : c ⟶ c') : PathProd p d c' :=
  match p, d, args with
  | .nil, _, ⟨f⟩ => ⟨f ≫ α⟩
  | Quiver.Path.cons _ _, _, args =>
    let ⟨e, h, inner⟩ := args; ⟨e, h, inner.mapR α⟩

/-- `mapL` and `mapR` commute: they act on independent components of `PathProd`. -/
theorem mapL_mapR_comm {C D : ProfCat.{v, u}} {d d' : D} {c c' : C}
    {p : Quiver.Path C D} (args : PathProd p d c) (α : c ⟶ c') (β : d' ⟶ d) :
    (args.mapL β).mapR α = (args.mapR α).mapL β := by
  induction p generalizing c c' with
  | nil =>
    match args with
    | ⟨f⟩ => simp [PathProd.mapL, PathProd.mapR, Category.assoc]
  | cons p H ih =>
    match args with
    | ⟨e, inner, h⟩ => rfl

/-- The profunctor structure on `PathProd` along a path from `C` to `D`.
This is a `Profunctor D C`, covariant in `D` (via `mapR`) and contravariant in `C`
(via `mapL`). -/
noncomputable def PathProd.toProfunctor {C D : ProfCat.{v, u}}
    (p : @Quiver.Path ProfCat _ C D) : Profunctor.{max u v} C D where
  obj d c := PathProd p d c
  map f g args := (args.mapR g).mapL f
  map_id := sorry
  map_comp := sorry

/-- Concatenation of path products: given path products for composable paths `p` and `q`,
produce a path product for the composition `p.comp q`. -/
def comp {C E D : ProfCat.{v, u}} {d : D} {e₀ : E} {c : C}
    {p : Quiver.Path C E} {q : Quiver.Path E D}
    (args_p : PathProd p e₀ c) (args_q : PathProd q d e₀) : PathProd (p.comp q) d c :=
  match D, q, d, args_q with
  | _, .nil, _, ⟨f⟩ => args_p.mapL f
  | _, Quiver.Path.cons _ _, _, args_q =>
    let ⟨f, h, inner_q⟩ := args_q; ⟨f, h, PathProd.comp args_p inner_q⟩

/-- Split a path product for a composed path into path products for the two parts.
Given `PathProd (p.comp q) d c`, produce an intermediate object `e₀ : E` together
with `PathProd p e₀ c` and `PathProd q d e₀`. -/
def split {C E D : ProfCat.{v, u}} {d : D} {c : C}
    {p : @Quiver.Path ProfCat _ C E} {q : @Quiver.Path ProfCat _ E D}
    (args : PathProd (p.comp q) d c) : (e₀ : E) × PathProd p e₀ c × PathProd q d e₀ :=
  match D, q, d, args with
  | _, .nil, d, args => ⟨d, args, ⟨𝟙 d⟩⟩
  | _, Quiver.Path.cons _ _, _, args =>
    let ⟨f, h, inner⟩ := args
    let ⟨e₀, p_part, q_part⟩ := PathProd.split inner
    ⟨e₀, p_part, ⟨f, h, q_part⟩⟩

end PathProd

/-! ## Wedge relation -/

/-- The wedge relation on `PathProd` identifies two tuples if they can be related
by sliding a morphism across an internal junction.

* `junction`: At the junction between sub-path `p` and edge `H`, for any `α : e ⟶ e'`,
  identifies `⟨e', inner.mapR α, h⟩` with `⟨e, inner, H.mapL α h⟩`.
  This captures the fact that acting on the right boundary of the sub-path with `α`
  is equivalent to acting on the left boundary of `H` with `α`.

* `inner`: Propagates wedge relations from the sub-path through the outer structure,
  keeping the outermost edge element fixed. -/
inductive WedgeRel {C : ProfCat.{v, u}} :
    {D : ProfCat.{v, u}} → {p : @Quiver.Path ProfCat _ C D} → {d : D} → {c : C} →
    PathProd p d c → PathProd p d c → Prop where
  | junction {D E : ProfCat.{v, u}} {p : @Quiver.Path ProfCat _ C E}
      {H : E ⟶ D} {d : D} {c : C} {e e' : E}
      (α : e' ⟶ e) (inner : PathProd p e c) (h : H.obj d e') :
      @WedgeRel _ _ (.cons p H) d c ⟨e', h, inner.mapL α⟩ ⟨e, H.mapR α h, inner⟩
  | inner {D E : ProfCat.{v, u}} {p : @Quiver.Path ProfCat _ C E}
      {H : E ⟶ D} {d : D} {c : C} {e : E}
      (h : H.obj d e) {x y : PathProd p e c} :
      @WedgeRel C E p e c x y →
        @WedgeRel C D (.cons p H) d c ⟨e, h, x⟩ ⟨e, h, y⟩

/-- The setoid on `PathProd` generated by the equivalence closure of the wedge relation.
Two path product elements are equivalent if they can be connected by a sequence of
wedge slides at internal junctions. -/
instance PathProd.setoid {C D : ProfCat.{v, u}} (p : @Quiver.Path ProfCat _ C D)
    (d : D) (c : C) : Setoid (PathProd p d c) where
  r := Relation.EqvGen (@WedgeRel C D p d c)
  iseqv := Relation.EqvGen.is_equivalence _

/-! ## Profunctor structure on PathProd -/

/-- Left action `mapL` preserves the wedge relation. -/
theorem PathProd.mapL_preserves_wedgeRel {C D : ProfCat.{v, u}}
    {p : @Quiver.Path ProfCat _ C D} {d : D} {c c' : C} (α : c ⟶ c')
    {x y : PathProd p d c} (h : @WedgeRel C D p d c x y) :
    @WedgeRel C D p d c' (x.mapR α) (y.mapR α) := by
  induction h with
  | junction β inner h =>
    sorry
  | inner h rel ih =>
    sorry

/-- Right action `mapR` preserves the wedge relation. -/
theorem PathProd.mapR_preserves_wedgeRel {C D : ProfCat.{v, u}}
    {p : @Quiver.Path ProfCat _ C D} {d d' : D} {c : C} (α : d' ⟶ d)
    {x y : PathProd p d c} (h : @WedgeRel C D p d c x y) :
    @WedgeRel C D p d' c (x.mapL α) (y.mapL α) := by
  sorry

/-! ## Functor tensor product -/

/-- The functor tensor product along a path of profunctors.
This is the quotient of `PathProd` by the equivalence relation generated by the wedge
conditions. Elements of `TensorProd p d c` represent equivalence classes of tuples
of profunctor elements along the path `p`, where adjacent profunctors are identified
via their shared boundary. -/
def TensorProd {C D : ProfCat.{v, u}} (p : @Quiver.Path ProfCat _ C D)
    (d : D) (c : C) : Type (max u v) :=
  Quotient (PathProd.setoid p d c)

/-- The canonical map from `PathProd` to `TensorProd`. -/
def TensorProd.mk {C D : ProfCat.{v, u}} {p : @Quiver.Path ProfCat _ C D}
    {d : D} {c : C} (args : PathProd p d c) : TensorProd p d c :=
  Quotient.mk _ args

/-- The profunctor structure on the functor tensor product, inherited from `PathProd`.
This is well-defined because `mapL` and `mapR` on `PathProd` preserve the wedge relation. -/
noncomputable def TensorProd.toProfunctor {C D : ProfCat.{v, u}}
    (p : @Quiver.Path ProfCat _ C D) : Profunctor.{max u v} C D where
  obj d c := TensorProd p d c
  map f g q := Quotient.lift
    (fun args => Quotient.mk _ ((args.mapR g).mapL f))
    (sorry)
    q
  map_id := sorry
  map_comp := sorry

end CategoryTheory
